sudo: false
language: php
php:
- 5.5
- 7.0
before_install:
- phpenv config-rm xdebug.ini
- composer global require hirak/prestissimo --no-interaction --no-suggest
- composer global require phpunit/phpunit
install:
- composer install --prefer-source --no-interaction --dev --ignore-platform-reqs --no-suggest
script:
- find ./src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
- phpunit
cache:
  directories:
  - vendor
  - "${HOME}/.cache/composer/files"
  - "${HOME}/.composer/cache/files"
jobs:
  include:
  - stage: automerge
    before_script:
    - git config --global user.name travis-ci[bot]
    - git config --global user.email travis[bot]@example.com
    - curl -o automerge.sh https://gist.githubusercontent.com/mijohansen/348f1daab99a8f64f2837330a48f3b15/raw/23767acbaca8f12b4e83fae1fc119e9a9d39c2a8/automerge.sh
    - chmod a+x automerge.sh
    script: BRANCHES_TO_MERGE_REGEX='^develop' BRANCH_TO_MERGE_INTO=master ./automerge.sh
    if: branch = develop
    php: 7.1
env:
  global:
    secure: Wfnb1rPgI9Wf9a8uMVKBk88dJJonRpjh8lnvxrCDOny0n8jFtFNprxNgkXnUjiO6FyZ+1zrYJNTUPwAU8ujD0KoZc4yc0MpdEhPgb1uEFyMKiWTjbmHCgiBPlvLtJa7PZEsyqzgkNYSq0VKRxA8my+7uApcRAK/hYydvAHWCFfMYYwpuNuJt3ugUzlf56x131nXJ9IuB8L17WFcGmApRgC/LIDBU6Ntu+pmYlXnbQKsevBh8svVMwL/4vCXGWnigeiqDTXyX+pCjZe9gljcg88Hu4o/2kPSZJGukZGf1MrbaEuYlCWkz8AJarhHo+iDvM/GMF5Ar9yaq+nldEH+rbnxBcFtEicfmJTu0d+RQy+ujFhu73geJC4R+3o3JnsLD61FTVfuV0K/laxhh51Q+n9MJ7Hh5EtYTnpZDFl5vud/p0jfeWRcqHRBwCrnZ9QlDqPTreEpfNT79YDk6Q04GaihnkB+1QxaPUPMI1Ftjb3KPll9JaMnjYNkaM0SN6Z/bI78kdAppuaJa1MZCO19xGLRadpYJHl+jJgjKV9tvfu2N0I2aYjsefhPOwRMiggg2sIhcagKl343d3hhm7cfc0Fm2BcW8V6SOGmd47jB62rD2zhPr+H/1kakrMfN71AzcEjNNY0ps0JflVoMeu3bFBU0qkEJoV4pxsVMwpz3jo0o=
